spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

metrix:
  security:
    jwt:
      secret-key: ${METRIX_SECURITY_JWT_SECRET_KEY}
  analytics:
    url: ${METRIX_ANALYTICS_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
